### PR TITLE
Better assemblyinfo handling.

### PR DESCRIPTION
**Pull request by stevek**
...ributes.  Fixes an error condition when updating a file versus rewriting it where a pre-defined custom attribute is written out twice.

Includes an assemblyinfo.update method, which is effectively to assemblyinfo.use.

Please let me know if this doesn't meet your expectations for a pull request.

### CODE REVIEW

**Comment by haf** [comment]
Could you please rebase this onto dev?

**Comment by haf** [comment]
@stevek - if you could do the rebase onto dev and add a failing test that your pull request makes passing, it would be great.

**Comment by stevek** [comment]
As soon as I get my head above water at work, it's yours. :)

**Comment by stevek** [comment]
Following up, that means by Monday latest.

**Comment by haf** [comment]
Awesome, looking forward to it :)

**Comment by stevek** [comment]
Still working on it.  Wrapping my head around the spec stuff is taking longer than I had anticipated.

**Comment by haf** [comment]
OK; we're planning on doing another coding session Sunday FYI; you could be a part of the skype conversation if you want.

**Comment by haf** [comment]
Done.

**Pull request closed without merging**
