### PR TITLE
Ilmerge

### PR DESCRIPTION
**Pull request by tkellogg**
Added an ILMerge task. Assumes ILMerge is installed in `C:\Program Files\Micrsoft\ILMerge`, `C:\Program Files (x86)\Microsoft\ILMerge`, or you can specify your own:

``` ruby
ilmerge :merge do |cfg|
  cfg.command = 'tools\ILMerge\ILMerge.exe'  # optional, if you have it installed within the repository
  cfg.assemblies 'build/assembly1.dll', 'build/assembly2.dll'
  cfg.output = 'build/master.dll'
end
```

It also supports all the typical `Albacore::RunCommand` methods.

### CODE REVIEW

**Comment by haf** [comment]
Nice, I'll see if I can merge this tomorrow.

**Comment by haf** [comment]
Of course, by tomorrow back then, other things happened. This pull request has a problem with it; it's based off master. Do you think you could submit this pull request for dev?

**Comment by tkellogg** [comment]
I rebased off of dev

**Comment by haf** [comment]
Unfortunately you seem to have rebased onto master as you saw it, i.e. you have kept your old ilmerge fixes on your own master, then transplanted all of the history of origin/master..origin/develop onto refs/master and then added and fixed your ILmerge on top of that to match dev. You can see this from the long list of commits this pull request has in it.

I'm going to cherry-pick now and merge it that way :)

**Comment by haf** [comment]
@tkellogg in the meanwhile - could you please provide a documentation page for it?

**Comment by haf** [comment]
Merged and pushed to dev. Tests seem to be passing. Thanks Tim!

**Pull request closed without merging**
