### PR TITLE
Prevent a failing of an entire rake script on an xUnit test fail.

### PR DESCRIPTION
**Pull request by ziez**
I'm building a project on the TeamCity. When the project tests failing, I'm still need to deploy the project artifacts. So, there will be nice to have a flag on the xUnit task which can prevent the rake script failing on the "red" test.
What do you think?

### CODE REVIEW

**Comment by mxriverlynn** [comment]
this has been pulled into the dev branch, in prep for next release.

thanks for all the contributions, recently. you've added a lot of great bits to the project. sorry it's taken so long to get your changes pulled in.

**Comment by mxriverlynn** [comment]
v0.2.6 has been released - can you update the wiki pages with the changes you made?

**Comment by ziez** [comment]
Sorry for the delay with an answer (I had a vacation last two weeks). I'll update the wiki in the next few days.

**Comment by mxriverlynn** [comment]
no problem, and thanks :)

**Pull request closed without merging**
