### PR TITLE
nuspec file generator task for creating NuGet "nuspec" files

### PR DESCRIPTION
**Pull request by stevehebert**
This task allows for the declaration of parameters for a nuget .nuspec file.  This task ensures that the minimum set of required tasks are declared and allows for all optional parameters including the file and dependency lists.

The following nuspec task declaration is used to describe how to build the nuget manifest which is used to package files.

<pre><code>
nuspec do |nuspec|
   nuspec.id="fluentworkflow"
   nuspec.output_file = "fluentworkflow.nuspec"
   nuspec.version = full_version
   nuspec.authors = "Steve Hebert"
   nuspec.description = "FluentWorkflow is a workflow/saga dsl and runtime component"
   nuspec.language = "en-US"
   nuspec.licenseUrl = "http://fluentworkflow.codeplex.com/license"
   nuspec.projectUrl = "http://fluentworkflow.codeplex.com"
   nuspec.working_directory = "Build/Deploy"
   nuspec.dependency "Autofac", "2.3.2.632"
   nuspec.dependency "Stateless"
   nuspec.file "bin/Debug/*.dll", "lib"
   nuspec.file "bin/Debug/*.pdb", "lib"
end
</code></pre>

This results in the following output being generated:
https://gist.github.com/789019

Note that working_directory is not required to be used - you could do all the pathing in the output_file attribute.

### CODE REVIEW

**Comment by thecodejunkie** [comment]
This looks nice! does it support packaging packages that a tied to a specific .net framework version? Like putting your assemblies in /lib/4.0  .. you can put different versions in the same package I believe .. In the nugets I have I put them in /lib/4.0/Foo.dll because they target the .net 4.0

**Comment by stevehebert** [comment]
It sure does.  The convention follows default behavior if you do not make any entries using the .files method which means files are relative to the nuspec file and have net4, 35, etc directories. On the other hand,you can make these definitions explicit using .file method where the first param is the file spec and the second is the lib folder name.   That second parameter is optional, following the nuspec definition in that respect.

**Comment by stevehebert** [comment]
To be clear, the nuspec task only creates the nuspec file.  There is a separate task under pull request now called nuget pack https://github.com/derickbailey/Albacore/pull/124

**Comment by thecodejunkie** [comment]
Sounds great! We'll definitely be putting this task to use when it's available :-)

**Comment by mxriverlynn** [comment]
pulled this into my local branch. working on other requests, too.

**Pull request closed without merging**
