### PR TITLE
Normalize number of blank lines at end of AssemblyInfo output

### PR DESCRIPTION
**Pull request by mhenry07**
This is to address issue #214, "AssemblyInfo rewrite adds additional blank line with every execution."

There may be a more efficient way to do it, but it now passes the test I wrote.

I think/hope my changes will be compatible with #213.

### CODE REVIEW

**Comment by mhenry07** [comment]
I just did a (local) test merging @cakirby's changes from #213 with my own. It merged cleanly and the assemblyinfo specs passed. :)

**Comment by haf** [comment]
Hey Mike,

We’re in the process of actually doing some releasin’ and codin’ on albacore, we have Anthony with us now, and have moved the repository to github.com/albacore

Could you send the pull request there perhaps, so we can try out our github-fu with the new repo?

Cheers,

Henrik

**Comment by mhenry07** [comment]
@haf, I just submitted the pull request Albacore/albacore#1.

I had to fork Albacore/albacore, add a remote for my original fork, and fetch/merge/push my changes from my original fork to the new fork. Is that the best way?

**Comment by haf** [comment]
@mhenry07 Yes, that's good. Closing this issue.

**Pull request closed without merging**
