### PR TITLE
Added functionality for MSdeploy

### PR DESCRIPTION
**Pull request by bluephlame**
Hi,

I have added some functionality to be able to do an MSDeploy from albacore. This is mainly focused around the deployment of a package to a server and not some of the more advanced features for cloning and synchronising servers.

This is my first git pull request so let me know if I have made any errors in the process. (I think I have but cannot figure out how to revert them) as i have
- bumped the version to 0.2.8
  - removed the albacore.gemspec file (Which was generated at any rate so not sure if this is OK)

I have also fixed issue #188 as this was causing an issue using nuget in our environment.

### CODE REVIEW

**Comment by haf** [comment]
Thank you for your pull request!

If you could rebase this onto dev, I'd be happy.

**Comment by bluephlame** [comment]
Ok,  

So I think I have rebased to dev. Let me know how I went :)

Thanks

**Comment by haf** [comment]
I'm sorry, but you didn't quite succeed in rebasing.

For the future reference, you write something like this:

```
$ g br
  chris
  dev
* master
$ g log

--> find the commit before you started hacking, a commit that is in OUR repo, with that_commit_hash as id.

$ g checkout that_commit_hash -b real_master
$ g checkout master
$ g rebase real_master
$ g branch -m master this_is_my_feature_branch
$ g push -u bluephlame this_is_my_feature_branch

--> go make pull request, select /develop
```

**Comment by haf** [comment]
Unfortunately your pull request causes the C# compiler to crash - could you try running `bundle exec rspec spec` in the albacore folder for me, **on the dev branch that I just pushed**?

**Comment by haf** [comment]
Also, `bundle exec rspec spec/msdeploy_spec.rb` gets me 

```
  12) MSDeploy Deploying a package from a zip file With specifying a bad parameter file, will throw an exception
     Failure/Error: lambda {@msdeploy.execute}.should raise_error(RuntimeError ,"Could not find parameter file specified
.")
```

and similar.

**Comment by haf** [comment]
Seems like there's some race condition in the compiler, it doesn't always crash. I'd be interested specifically comments on the msdeploy_spec.rb file, not the csc one.

**Comment by shawnmclean** [comment]
Is this in production yet?

**Comment by haf** [comment]
Is that a question for me? It's not in master no... I'm waiting for some feedback here... Otherwise, if I don't get any feedback and I can't solve it within an hour, I'll revert the commit and publish 0.3 finally.

**Comment by bluephlame** [comment]
I'll get on to this today. I'm in Sydney so our time zones are out of sync. The error may be because you do not have msdeploy installed but the errors look bad if thats the case.

**Comment by haf** [comment]
Could you then please place in in the support folder so that the test can be run without having to manually install tools?

**Comment by bluephlame** [comment]
So I have done another pull request (hopefully with the correct re base this time) it now has the MSdeploy executables and the some additions to the spec tests so they fail gracefully if MSDeploy is not installed.

**Comment by pavanmishra** [comment]
@bluephlame there might be something to look at in issue #210. Its about exec task failing even after successful execution of MSDeploy. There are references in discussion which discuss about msdeploy returning exit code of 0 in events of success and failure both. 

@AnthonyMastrean  suggested to bring this to discussion here.

**Comment by haf** [comment]
I'm trying to get a clean tree merged - it's already been implemented...

**Comment by AnthonyMastrean** [comment]
@bluephlame, any chance you can write some [documentation](https://github.com/Albacore/albacore/wiki/MSDeploy-Task) for this task?

**Comment by gilles-leblanc** [comment]
I would also vote for some documentation.

**Pull request closed without merging**
